#Web服务器：apache | nginx，通过交互式选择获取
moodle_webs: apache

moodle_vhost_dir: /etc/httpd/vhost
moodle_vhost_src: vhost.conf
moodle_service: httpd
moodle_owner: apache
moodle_db_password: "123456"
moodle_name: "moodle"
moodle_title: "Moodle"
#下载链接需定期维护，注意：地址中一定要带上“direct”，否则ansible不能下载
moodle_download_url: "https://download.moodle.org/download.php/direct/stable310/moodle-3.10.1.zip"
