#Moodle版本，需定期维护
moodle_version: v3.8.1

#Web服务器：apache | nginx，通过交互式选择获取
moodle_webs: apache

# 默认值
moodle_vhost_dir: /etc/httpd/vhost
moodle_vhost_src: vhost.conf
moodle_service: httpd
moodle_owner: apache

php_runtime_meta:
  CentOS:
    apache:
      vhost_dir: /etc/httpd/vhost
      vhost_src: vhost.conf
      service: httpd
      owner: apache
    nginx:
      vhost_dir: /etc/nginx/conf.d
      vhost_src: default.conf
      service: nginx
      owner: apache
  Ubuntu:
    apache:
      vhost_dir: /etc/apache2/sites-enabled
      vhost_src: vhost.conf
      service: apache2
      owner: www-data
    nginx:
      host_dir: /etc/nginx/conf.d
      vhost_src: default.conf
      service: nginx
      owner: www-data