#Moodle版本，需定期维护
moodle_version: v3.8.1

#Web服务器：apache | nginx，通过交互式选择获取
moodle_webs: apache

moodle_vhost_dir: moodle_runtime_meta.CentOS.apache.vhost_dir
moodle_vhost_src: moodle_runtime_meta.CentOS.apache.vhost_src
moodle_service: moodle_runtime_meta.CentOS.apache.service
moodle_owner: moodle_runtime_meta.CentOS.apache.owner
